LanguageCode = "zh-cn"
title = "天空之城"
hasCJKLanguage = true
theme = "Mainroad"
summaryLength = "145"
defaultContentLanguage = "zh-cn"
    
[Params]
  description = "专注于Java、Go、Kubernetes、Docker、Harbor、Helm等容器相关技术方向开发"
  subtitle = "代码沉淀技术，技术成就梦想!   Hugo、Java、Go、Docker、Harbor、Kubernetes~"
  keywords = "天空之城Hugo,Go,Kubernetes,Docker,博客,静态博客"
  readmore = true
  dateformat = "2006-01-02"
  post_navigation = true
  post_related = true
  share_open = true
  baidu_push = true
  baidu_count_id = "1f38fa809"
  authorbox = true
  isso_open = true
  friend_link_open = true
  toc = true
  share_top_show = true
  
[Author] # Used in authorbox
  name = "文章作者kingfsen"
  bio = "一个不会写Bug的后端开发工程师，擅长Java、Go等编程语言。"
  avatar = "img/avatar.png"
  
[[Params.friendlink]]
  link = "https://youendless.com"
  title = "天空之城"
  desc = "一个专注于容器技术的博客"
  
[[Params.friendlink]]
  link = "https://youendless.com"
  title = "天空之城"
  desc = "一个专注于容器技术的博客"
  
[Params.isso]
  prefix = "isso"

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "languages", "recent", "categories", "taglist", "social", "friendlink"]

[Params.widgets]
  recent_num = 10
  tags_counter = true

[menu]
[[menu.main]]
  identifier = "post"
	name = "博客"
	title = "技术博客文章"
	url = "/post/"

[[menu.main]]
  identifier = "about"
	name = "关于我"
	title = "博客作者的资料信息"
	url = "/about/"
	
[[menu.main]]
  identifier = "timeline"
	name = "时间轴"
	title = "博客创作时间轨迹"
	url = "/timeline/"
	
[Params.widgets.social]
  github = "kingfsen"
  email = "qq.com"
  
[related]
   threshold = 80
   includeNewer = true
   toLower = true
   [[related.indices]]
     name = "tags"
	 weight = 100
